// Code generated by goctl. DO NOT EDIT.
package types

type AdminUserLoginReq struct {
	Account  string `json:"account"`  //账号，系统唯一
	Password string `json:"password"` //密码
}

type AdminUserLoginResp struct {
	Token string `json:"token"` //登录成功返回的token
}

type CreateAdminUserReq struct {
	Account  string `json:"account"`  //登录账号
	Name     string `json:"name"`     //账号名称
	Password string `json:"password"` //密码
	RoleId   int64  `json:"roleId"`   //系统角色ID
}

type CreateAdminUserResp struct {
	Id int64 `json:"id"` //用户ID
}
