// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminUser "go-api/internal/handler/adminUser"
	"go-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: swaggerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/userLogin",
				Handler: adminUser.AdminLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/createUser",
				Handler: adminUser.CreateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/deleteUser",
				Handler: adminUser.DeleteUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/userList",
				Handler: adminUser.UserListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/updateUser",
				Handler: adminUser.UpdateUserHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/adminUser/getOneUser",
				Handler: adminUser.GetOneUserHandler(serverCtx),
			},
		},
	)
}
