// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	demo "go-api/internal/handler/demo"
	"go-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/swagger",
				Handler: swaggerHandler(serverCtx),
			},
		},
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/do/demo",
				Handler: demo.DoDemoHandler(serverCtx),
			},
		},
	)
}
